### ISSUE TITLE
go2rtc WebUI

### ISSUE THREAD

**Issue by otebono** [cxnturi0n/grafana-livecamera-rtsp-webrtc#1]
I cannot access the web interface of go2rtc when I deploy the container. 

Is any additional configuration necessary? I have enabled incoming connections on the firewall for port 1984.

The container's log is as follows:

2024-07-07 10:29:28 10:29:28.755 INF go2rtc platform=linux/amd64 revision=a4885c2 version=1.9.4
2024-07-07 10:29:28 10:29:28.755 INF config path=/config/go2rtc.yaml
2024-07-07 10:29:28 10:29:28.756 INF [api] listen addr=:1984
2024-07-07 10:29:28 10:29:28.756 INF [rtsp] listen addr=:8554
2024-07-07 10:29:28 10:29:28.756 INF [webrtc] listen addr=:8555/tcp

**Comment by cxnturi0n** [comment]
No additional configuration is needed, it should work out of the box. Try to reach go2rtc WebUI from here: http://127.0.0.1:1984/ , perhaps you do not have "localhost" in your _hosts_ file.

**Comment by otebono** [comment]
Now I'm reaching WebUI deleting network_mode and binding ports in the docker compose file. 

However, I have the problem that it does not detect the usb webcam.  Nothing appears in FFmpeg Devices (USB) menu. When deploying the application directly in Windows, nothing appears either.

My webcam is a Logitech C920 Carl Zeiss 1080p.

**Comment by otebono** [comment]
I've already got it working. Now the problem I have is that iframe doesn't show in grafana. It appears as plain text:

"<iframe width="1000" height="1000" src="http://localhost:1984/stream.html?src=virtual&mode=webrtc"> </iframe>"

EDIT: You need to allow embedding in the config of grafana

All working now, thank you!!
